# Generated by Django 3.2.8 on 2023-09-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20230904_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesstion_start', models.CharField(max_length=100)),
                ('sesstion_end', models.CharField(max_length=100)),
            ],
        ),
    ]
